// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_fsm.sql

package db

import (
	"context"
)

const clearFSM = `-- name: ClearFSM :exec
DELETE FROM bot_fsm WHERE tg_id = $1
`

func (q *Queries) ClearFSM(ctx context.Context, tgID int64) error {
	_, err := q.db.ExecContext(ctx, clearFSM, tgID)
	return err
}

const getFSM = `-- name: GetFSM :one
SELECT state, data FROM bot_fsm WHERE tg_id = $1
`

type GetFSMRow struct {
	State string
	Data  string
}

func (q *Queries) GetFSM(ctx context.Context, tgID int64) (GetFSMRow, error) {
	row := q.db.QueryRowContext(ctx, getFSM, tgID)
	var i GetFSMRow
	err := row.Scan(&i.State, &i.Data)
	return i, err
}

const setFSM = `-- name: SetFSM :exec
INSERT INTO bot_fsm (tg_id, state, data, updated_at)
VALUES ($1, $2, $3, FLOOR(EXTRACT(EPOCH FROM now()))::bigint)
ON CONFLICT (tg_id) DO UPDATE SET
    state = excluded.state,
    data = excluded.data,
    updated_at = FLOOR(EXTRACT(EPOCH FROM now()))::bigint
`

type SetFSMParams struct {
	TgID  int64
	State string
	Data  string
}

func (q *Queries) SetFSM(ctx context.Context, arg SetFSMParams) error {
	_, err := q.db.ExecContext(ctx, setFSM, arg.TgID, arg.State, arg.Data)
	return err
}
