// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package db

import (
	"context"
)

const getApplicantCache = `-- name: GetApplicantCache :one
SELECT data, updated_at FROM applicant_cache WHERE name = ?
`

type GetApplicantCacheRow struct {
	Data      string
	UpdatedAt int64
}

func (q *Queries) GetApplicantCache(ctx context.Context, name string) (GetApplicantCacheRow, error) {
	row := q.db.QueryRowContext(ctx, getApplicantCache, name)
	var i GetApplicantCacheRow
	err := row.Scan(&i.Data, &i.UpdatedAt)
	return i, err
}

const getProgramCache = `-- name: GetProgramCache :one
SELECT data, updated_at FROM program_cache WHERE url = ?
`

type GetProgramCacheRow struct {
	Data      string
	UpdatedAt int64
}

func (q *Queries) GetProgramCache(ctx context.Context, url string) (GetProgramCacheRow, error) {
	row := q.db.QueryRowContext(ctx, getProgramCache, url)
	var i GetProgramCacheRow
	err := row.Scan(&i.Data, &i.UpdatedAt)
	return i, err
}

const putApplicantCache = `-- name: PutApplicantCache :exec
INSERT INTO applicant_cache (name, data, updated_at)
VALUES (?1, ?2, unixepoch())
ON CONFLICT(name) DO UPDATE SET
    data = excluded.data,
    updated_at = unixepoch()
`

type PutApplicantCacheParams struct {
	Name string
	Data string
}

func (q *Queries) PutApplicantCache(ctx context.Context, arg PutApplicantCacheParams) error {
	_, err := q.db.ExecContext(ctx, putApplicantCache, arg.Name, arg.Data)
	return err
}

const putProgramCache = `-- name: PutProgramCache :exec
INSERT INTO program_cache (url, data, updated_at)
VALUES (?1, ?2, unixepoch())
ON CONFLICT(url) DO UPDATE SET
    data = excluded.data,
    updated_at = unixepoch()
`

type PutProgramCacheParams struct {
	URL  string
	Data string
}

func (q *Queries) PutProgramCache(ctx context.Context, arg PutProgramCacheParams) error {
	_, err := q.db.ExecContext(ctx, putProgramCache, arg.URL, arg.Data)
	return err
}

const vacuumApplicantCache = `-- name: VacuumApplicantCache :exec
DELETE FROM applicant_cache WHERE updated_at < ?
`

func (q *Queries) VacuumApplicantCache(ctx context.Context, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, vacuumApplicantCache, updatedAt)
	return err
}

const vacuumProgramCache = `-- name: VacuumProgramCache :exec
DELETE FROM program_cache WHERE updated_at < ?
`

func (q *Queries) VacuumProgramCache(ctx context.Context, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, vacuumProgramCache, updatedAt)
	return err
}
