// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type ApplicantCache struct {
	Name      string
	Data      string
	UpdatedAt int64
}

type BotFsm struct {
	TgID      int64
	State     string
	Data      string
	UpdatedAt int64
}

type ProgramCache struct {
	URL       string
	Data      string
	UpdatedAt int64
}

type SavedList struct {
	ID         int64
	UserTgID   int64
	Name       string
	URL        string
	Data       string
	CreatedAt  int64
	ShareToken string
}

type User struct {
	TgID           int64
	NmtScores      string
	Settings       string
	Activates      int64
	RightActivates int64
	CreatedAt      int64
	UpdatedAt      int64
}
