// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_lists.sql

package db

import (
	"context"
)

const deleteSavedList = `-- name: DeleteSavedList :exec
DELETE FROM saved_lists WHERE id = ?
`

func (q *Queries) DeleteSavedList(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSavedList, id)
	return err
}

const getSavedList = `-- name: GetSavedList :one
SELECT id, user_tg_id, name, url, data, created_at FROM saved_lists WHERE id = ?
`

func (q *Queries) GetSavedList(ctx context.Context, id int64) (SavedList, error) {
	row := q.db.QueryRowContext(ctx, getSavedList, id)
	var i SavedList
	err := row.Scan(
		&i.ID,
		&i.UserTgID,
		&i.Name,
		&i.URL,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listSavedLists = `-- name: ListSavedLists :many
SELECT id, user_tg_id, name, url, data, created_at FROM saved_lists
WHERE user_tg_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSavedLists(ctx context.Context, userTgID int64) ([]SavedList, error) {
	rows, err := q.db.QueryContext(ctx, listSavedLists, userTgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedList{}
	for rows.Next() {
		var i SavedList
		if err := rows.Scan(
			&i.ID,
			&i.UserTgID,
			&i.Name,
			&i.URL,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveList = `-- name: SaveList :one
INSERT INTO saved_lists (user_tg_id, name, url, data)
VALUES (?, ?, ?, ?)
RETURNING id
`

type SaveListParams struct {
	UserTgID int64
	Name     string
	URL      string
	Data     string
}

func (q *Queries) SaveList(ctx context.Context, arg SaveListParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveList,
		arg.UserTgID,
		arg.Name,
		arg.URL,
		arg.Data,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateSavedListData = `-- name: UpdateSavedListData :exec
UPDATE saved_lists SET data = ?2 WHERE id = ?1
`

type UpdateSavedListDataParams struct {
	ID   int64
	Data string
}

func (q *Queries) UpdateSavedListData(ctx context.Context, arg UpdateSavedListDataParams) error {
	_, err := q.db.ExecContext(ctx, updateSavedListData, arg.ID, arg.Data)
	return err
}
