// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const addActivates = `-- name: AddActivates :exec
INSERT INTO users (tg_id, activates, updated_at)
VALUES ($1, $2, FLOOR(EXTRACT(EPOCH FROM now()))::bigint)
ON CONFLICT (tg_id) DO UPDATE SET
    activates = users.activates + excluded.activates,
    updated_at = FLOOR(EXTRACT(EPOCH FROM now()))::bigint
`

type AddActivatesParams struct {
	TgID      int64
	Activates int64
}

// Adds a batched delta accumulated in memory (the hot path buffers the
// per-update +1s and a periodic flush applies them in one write).
func (q *Queries) AddActivates(ctx context.Context, arg AddActivatesParams) error {
	_, err := q.db.ExecContext(ctx, addActivates, arg.TgID, arg.Activates)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT tg_id, nmt_scores, settings, activates, right_activates, created_at, updated_at FROM users WHERE tg_id = $1
`

func (q *Queries) GetUser(ctx context.Context, tgID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, tgID)
	var i User
	err := row.Scan(
		&i.TgID,
		&i.NmtScores,
		&i.Settings,
		&i.Activates,
		&i.RightActivates,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserNMT = `-- name: GetUserNMT :one
SELECT nmt_scores FROM users WHERE tg_id = $1
`

func (q *Queries) GetUserNMT(ctx context.Context, tgID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserNMT, tgID)
	var nmt_scores string
	err := row.Scan(&nmt_scores)
	return nmt_scores, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT settings FROM users WHERE tg_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, tgID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, tgID)
	var settings string
	err := row.Scan(&settings)
	return settings, err
}

const incrementActivates = `-- name: IncrementActivates :exec
INSERT INTO users (tg_id, activates, updated_at)
VALUES ($1, 1, FLOOR(EXTRACT(EPOCH FROM now()))::bigint)
ON CONFLICT (tg_id) DO UPDATE SET
    activates = users.activates + 1,
    updated_at = FLOOR(EXTRACT(EPOCH FROM now()))::bigint
`

// Race-safe counter increment (the Python version had a read-modify-write race).
func (q *Queries) IncrementActivates(ctx context.Context, tgID int64) error {
	_, err := q.db.ExecContext(ctx, incrementActivates, tgID)
	return err
}

const incrementRightActivates = `-- name: IncrementRightActivates :exec
INSERT INTO users (tg_id, right_activates, updated_at)
VALUES ($1, 1, FLOOR(EXTRACT(EPOCH FROM now()))::bigint)
ON CONFLICT (tg_id) DO UPDATE SET
    right_activates = users.right_activates + 1,
    updated_at = FLOOR(EXTRACT(EPOCH FROM now()))::bigint
`

func (q *Queries) IncrementRightActivates(ctx context.Context, tgID int64) error {
	_, err := q.db.ExecContext(ctx, incrementRightActivates, tgID)
	return err
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT tg_id FROM users ORDER BY tg_id
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var tg_id int64
		if err := rows.Scan(&tg_id); err != nil {
			return nil, err
		}
		items = append(items, tg_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserNMT = `-- name: SetUserNMT :exec
INSERT INTO users (tg_id, nmt_scores, updated_at)
VALUES ($1, $2, FLOOR(EXTRACT(EPOCH FROM now()))::bigint)
ON CONFLICT (tg_id) DO UPDATE SET
    nmt_scores = excluded.nmt_scores,
    updated_at = FLOOR(EXTRACT(EPOCH FROM now()))::bigint
`

type SetUserNMTParams struct {
	TgID      int64
	NmtScores string
}

func (q *Queries) SetUserNMT(ctx context.Context, arg SetUserNMTParams) error {
	_, err := q.db.ExecContext(ctx, setUserNMT, arg.TgID, arg.NmtScores)
	return err
}

const setUserSettings = `-- name: SetUserSettings :exec
INSERT INTO users (tg_id, settings, updated_at)
VALUES ($1, $2, FLOOR(EXTRACT(EPOCH FROM now()))::bigint)
ON CONFLICT (tg_id) DO UPDATE SET
    settings = excluded.settings,
    updated_at = FLOOR(EXTRACT(EPOCH FROM now()))::bigint
`

type SetUserSettingsParams struct {
	TgID     int64
	Settings string
}

func (q *Queries) SetUserSettings(ctx context.Context, arg SetUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setUserSettings, arg.TgID, arg.Settings)
	return err
}

const topUserByActivates = `-- name: TopUserByActivates :one
SELECT tg_id, activates FROM users
ORDER BY activates DESC, tg_id ASC
LIMIT 1
`

type TopUserByActivatesRow struct {
	TgID      int64
	Activates int64
}

func (q *Queries) TopUserByActivates(ctx context.Context) (TopUserByActivatesRow, error) {
	row := q.db.QueryRowContext(ctx, topUserByActivates)
	var i TopUserByActivatesRow
	err := row.Scan(&i.TgID, &i.Activates)
	return i, err
}

const totalActivates = `-- name: TotalActivates :one
SELECT
    COALESCE(SUM(activates), 0)::bigint       AS total_activates,
    COALESCE(SUM(right_activates), 0)::bigint AS total_right_activates
FROM users
`

type TotalActivatesRow struct {
	TotalActivates      int64
	TotalRightActivates int64
}

func (q *Queries) TotalActivates(ctx context.Context) (TotalActivatesRow, error) {
	row := q.db.QueryRowContext(ctx, totalActivates)
	var i TotalActivatesRow
	err := row.Scan(&i.TotalActivates, &i.TotalRightActivates)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (tg_id) VALUES ($1)
ON CONFLICT (tg_id) DO NOTHING
`

// Creates the user row if missing; safe to call on every interaction.
func (q *Queries) UpsertUser(ctx context.Context, tgID int64) error {
	_, err := q.db.ExecContext(ctx, upsertUser, tgID)
	return err
}
